name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "[0-9][0-9][0-9][0-9].[1-9][0-2]?.[0-9]+"
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify version
        run: |
          CONST_VERSION=$(grep -oP '^_PACKAGE_VERSION:.*$' pyvelop/const.py | grep -oP '[0-9]{4}\.[1-9]+[1-2]*\.[0-9]+')
          if [ "${{ $GITHUB_REF_NAME }}" != "$CONST_VERSION" ]; then
            echo "Version in code ($CONST_VERSION) doesn't match git version tag (${{ $GITHUB_REF_NAME }})!"
            exit 1
          fi
